### ISSUE TITLE
lua startup script - error

### ISSUE THREAD

**Issue by Strugglemeat** [cyneprepou4uk/BZK-6502-Disassembler#2]
> File:25: bad argument #1 to 'match' (string expected, got nil)
> stack traceback:
> 	[C]: in method 'match'
> 	File:25: in function <File:9>

line 25:            ` for m in editor:match(selection) do`

what should I do? I've got a good cdl and I think good asm output, trying to get to the next step.

**Comment by cyneprepou4uk** [comment]
That's weird, never happened to me before.

Try updating LuaScript plugin in Notepad++, current version should be 0.10 or 0.11, I don't remember exactly. If Plugins Admin shows some lower version, you should update Notepad++ and try again.

If nothing works, you can just remove lines from 9 to 43 in order to delete the npp.AddEventHandler function, and restart Notepad++.

**Comment by cyneprepou4uk** [comment]
I'm currently using Notepad++ v8.2.1 (64-bit), because newer versions have problems with LuaScript plugin (which is 0.11 at the moment).

If your problem is still occuring even with this version, and you want to use this "show matches" function, at line 16 replace
`if SELECTION ~= selection then`
with
`if SELECTION ~= selection and selection ~= nil then`
and then restart Notepad++.

By the way, can you post a screenshot where this error message is printed? And what version were you using?

**Comment by Strugglemeat** [comment]
npp.8.4.2.portable.x64 under Wine

changing line 16 as you specified above seems to have removed the error issue

**Comment by cyneprepou4uk** [comment]
That's good
